### ISSUE TITLE
Ошибка в функции flatten-minin.js

### ISSUE THREAD

**Issue by wareset** [stepancar/Big-Oops.js#1]
Файл https://github.com/stepancar/Big-Oops.js/blob/main/src/implementations/flatten-minin.js
Строка №7

Вместо `res.push(flat[i]);`
нужно `res.push(flat[j]);`

**Comment by stepancar** [comment]
@wareset ,вы правы, спасибо! Исправил.
FYI в этом репозитории исходники для сравнения больше не хранятся, я удалю  этот файл
